fixtures:
  repositories:
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
      ref: 2.1.0
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    epel: git://github.com/stahnma/puppet-module-epel.git
  symlinks:
    docker: "#{source_dir}"
