fixtures:
#  forge_modules:
#    - 'puppetlabs-stdlib'
#    - 'stahnma-epel'
  repositories:
    apt:
      repo: https://github.com/puppetlabs/puppetlabs-apt.git
      ref: 2.1.0
    puppetlabs-stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib
    epel:
      repo: https://github.com/stahnma/puppet-module-epel
  symlinks:
    docker: "#{source_dir}"
