fixtures:
  forge_modules:
    stdlib: 'puppetlabs-stdlib'
    epel: 'stahnma-epel'
    powershell: 'puppetlabs/powershell'
  repositories:
    apt:
      repo: git://github.com/puppetlabs/puppetlabs-apt.git
      ref: 2.1.0
  symlinks:
    docker: "#{source_dir}"
