name        'garethr-docker'
version     '0.9.0'
source      'git://github.com/garethr/garethr-docker.git'
author      'Gareth Rushgrove'
summary     'Module for installing docker from repository on get.docker.io'
description 'Install the official docker packages'
license     'Apache License, Version 2.0'

dependency  'puppetlabs/apt', '>= 1.1.0'
dependency  'puppetlabs/stdlib', '>=4.1.0'
